import { Box } from "./Box";
import { Content } from "./Content";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Box
          css={{
            maxW: "100%",
          }}
        >
          {children}
          <Content />
        </Box>
      </body>
    </html>
  );
}
